import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeftBar } from "../src/pages/chat/ui/left-bar/LeftBar";
import { Provider } from "react-redux";
import { store } from "./store/store";
import { StoreProvider } from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <div className="flex justify-center h-full">
            <div className="w-1/6 bg-zinc-900 hidden sm:hidden md:block">
              <LeftBar className="text-white px-2 py-2 w-full h-screen " />
            </div>
            <div className="md:w-5/6 w-full">{children}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
