import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeftBar } from "@/pages/chat/ui/left-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center h-full">
          <div className="w-1/6 bg-zinc-900 hidden sm:hidden md:block">
            <LeftBar className="text-white w-full h-screen " />
          </div>
          <div className="md:w-5/6 w-full max-h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
